services:
  - type: web
    name: skyline
    runtime: python

    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn --bind 0.0.0.0:$PORT config.wsgi:application

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: "skyline-tra1.onrender.com,skyline-2.onrender.com"
